import DocsLayout from "@/components/DocsLayout";
import { Streamdown } from "streamdown";

const content = `
# Agent Guide

Welcome to the Agent Program! This guide will walk you through the tools available to you for tracking the revenue generated by the users you've referred to the platform.

## 1. Introduction to the Agent Program

### 1.1. Your Role as an Agent

As an agent, your primary role is to bring new users to the platform. You earn a commission based on the "true revenue" generated by these users. "True revenue" is defined as the cost of deployments that are paid for with purchased credits, not free or awarded credits.

## 2. Revenue Reports

All of your reporting tools are located on the **Credits** page. You can access this page by clicking on the "Credits" link in the main navigation bar.

Once on the Credits page, you will see two tabs available to you: **User Revenue** and **Module Revenue**.

### 2.1. User Revenue Tab

This tab provides a detailed breakdown of the revenue generated by each of your referred users.

**Functionality**: This report shows you a list of all deployments made by your referred users that have generated true revenue. You can see the deployment ID, the module that was deployed, the date of the deployment, the credit cost, the revenue generated, and the user's email.

**Filtering**: You can filter this report to narrow down the data:
- **By User**: Select one or more users from the dropdown to see only their revenue-generating deployments.
- **By Date**: Use the start and end date pickers to see data from a specific time period.

**Exporting**: Once you have fetched the data, you can click the **Export to CSV** button to download the current view as a CSV file for your own records or further analysis.

### 2.2. Module Revenue Tab

This tab provides a high-level overview of the revenue generated by each module across all of your referred users.

**Functionality**: This report shows you the total revenue generated by each module. This can help you understand which modules are most popular and profitable among your referred users.

**Filtering**: You can filter this report to see data for specific modules or from a specific time period:
- **By Module**: Select one or more modules from the dropdown to see their total revenue.
- **By Date**: Use the start and end date pickers to see data from a specific time period.

**Exporting**: Once you have fetched the data, you can click the **Export to CSV** button to download the current view as a CSV file for your own records or further analysis.

By using these tools, you can effectively track your performance as an agent and identify opportunities for growth.

## 3. Help and Support

The **Help** page is your central resource for documentation and support. It contains:

- **User Guides**: Access to the Admin, Partner, Agent, and User guides.
- **Support Form**: A form to send a message directly to the support team.

## 4. Theme Customization

You can switch between light and dark themes to suit your preference. The theme selector is located in the user menu in the top-right corner of the navigation bar.
`;

export default function AgentGuide() {
  return (
    <DocsLayout>
      <article className="prose prose-slate dark:prose-invert max-w-none">
        <Streamdown>{content}</Streamdown>
      </article>
    </DocsLayout>
  );
}
